---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  namespace: minio
  name: minio
spec:
  interval: 5m
  url: https://charts.min.io/

---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno

---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx

---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets

---
apiVersion: v1
kind: Namespace
metadata:
  name: database-system

