---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  namespace: external-secrets
  name: external-secrets
spec:
  interval: 5m
  url: https://charts.external-secrets.io/index.yaml

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: external-secrets
  name: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      version: ~0.19.2
  dependsOn: []
  interval: 5m
  releaseName: external-secrets
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
