---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: metrics-system
  name: tempo
spec:
  chart:
    spec:
      chart: tempo
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: ~1.23.3
  dependsOn: []
  interval: 5m
  releaseName: tempo
  upgrade:
    remediation:
      remediateLastFailure: true
  values: