---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: metrics-system
  name: loki
spec:
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: ~2.10.2
  dependsOn: []
  interval: 5m
  releaseName: loki
  upgrade:
    remediation:
      remediateLastFailure: true
  values: