---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  namespace: metrics-system
  name: metrics-server
spec:
  interval: 5m
  url: https://kubernetes-sigs.github.io/metrics-server

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  namespace: metrics-system
  name: prometheus-community
spec:
  interval: 5m
  url: https://prometheus-community.github.io/helm-charts

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  namespace: metrics-system
  name: grafana
spec:
  interval: 5m
  url: https://grafana.github.io/helm-charts

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  namespace: metrics-system
  name: keda
spec:
  interval: 5m
  url: https://kedacore.github.io/charts