---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: metrics-system
  name: keda
spec:
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: keda
      version: ~2.17.2
  dependsOn: []
  interval: 5m
  releaseName: keda
  upgrade:
    remediation:
      remediateLastFailure: true
  values: